// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(FinalProjectDbContext))]
    [Migration("20180820154358_Second")]
    partial class Second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Area_Reparacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.Property<int>("descripcion");

                    b.HasKey("Id");

                    b.ToTable("Area_Reparacions");
                });

            modelBuilder.Entity("Models.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteId");

                    b.Property<string>("ClienteId1");

                    b.Property<int>("Hora_LLegada");

                    b.Property<int>("Hora_salida");

                    b.Property<string>("detalle");

                    b.Property<DateTime>("fecha");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId1");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("Models.Cliente", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellido");

                    b.Property<string>("Cedula");

                    b.Property<string>("Nombre");

                    b.Property<string>("direccion");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Models.Departamentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.Property<int>("descripcion");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contraseña");

                    b.Property<string>("Usario");

                    b.HasKey("Id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Models.Empleado_Atiende", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteId");

                    b.Property<string>("ClienteId1");

                    b.Property<int>("EmpleadoId");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId1");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Empleado_Atiendes");
                });

            modelBuilder.Entity("Models.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Area_ReparacionId");

                    b.Property<string>("Costo");

                    b.Property<string>("Garantia");

                    b.HasKey("Id");

                    b.HasIndex("Area_ReparacionId");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Models.Mantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FacturaId");

                    b.Property<DateTime>("Fecha_entrada");

                    b.Property<DateTime>("Fecha_salida");

                    b.Property<int>("MecanicosId");

                    b.Property<int>("VehiculoId");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.HasIndex("MecanicosId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Mantenimientos");
                });

            modelBuilder.Entity("Models.Mecanicos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.Property<int>("departamentosId");

                    b.HasKey("Id");

                    b.HasIndex("departamentosId");

                    b.ToTable("Mecanicos");
                });

            modelBuilder.Entity("Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteId");

                    b.Property<string>("ClienteId1");

                    b.Property<string>("Matricula");

                    b.Property<string>("Modelo");

                    b.Property<string>("agencia");

                    b.Property<int>("anio");

                    b.Property<string>("estado");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId1");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("Models.Cita", b =>
                {
                    b.HasOne("Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId1");
                });

            modelBuilder.Entity("Models.Empleado_Atiende", b =>
                {
                    b.HasOne("Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId1");

                    b.HasOne("Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Models.Factura", b =>
                {
                    b.HasOne("Models.Area_Reparacion", "Area_Reparacion")
                        .WithMany()
                        .HasForeignKey("Area_ReparacionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Models.Mantenimiento", b =>
                {
                    b.HasOne("Models.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Models.Mecanicos", "Mecanicos")
                        .WithMany()
                        .HasForeignKey("MecanicosId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Models.Mecanicos", b =>
                {
                    b.HasOne("Models.Departamentos", "departamentos")
                        .WithMany()
                        .HasForeignKey("departamentosId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Models.Vehiculo", b =>
                {
                    b.HasOne("Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId1");
                });
#pragma warning restore 612, 618
        }
    }
}
